# Generated by Django 5.0.3 on 2024-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='licence2_plate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='licence_plate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='vehicle2_make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='vehicle2_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
