# Generated by Django 5.0.3 on 2024-04-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_registration_licence2_plate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='licence2_plate',
            new_name='license2_plate',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='licence_plate',
            new_name='license_plate',
        ),
    ]
