# Generated by Django 5.0.3 on 2024-04-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_rename_licence2_plate_registration_license2_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
