# Generated by Django 5.0.3 on 2024-04-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_registration_first_name_registration_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='color2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='employee_id_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_id_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
